### ISSUE TITLE
Name 'sleep' is not defined

### ISSUE THREAD

**Issue by victoriatomzik** [eggplants/wbsv-cli#18] opened 2020-03-28 20:41 UTC
![image](https://user-images.githubusercontent.com/17315148/77833309-bd87ee00-713c-11ea-9561-3ae8719f968f.png)
[!]API says:TooManyRedirects!
[!]Need a 1min break...
[!]class 'NameError'
[!]name 'sleep' is not defined
[!]traceback object at 0x103bdb240

can we do something with it? :)

**Comment by eggplants** [comment] 2020-03-29 19:24
This bug was caused by my fault: not `sleep()` but `time.sleep()`
I fixed in `ver 0.1.2`. Thank you for your reporting!

**Closed as completed by eggplants** 2020-03-29 19:24 UTC
Labels: bug

**Comment by eggplants** [comment] 2020-03-29 19:29
Please `pip install -U wbsv` or `pip3 install -U wbsv`

**Comment by victoriatomzik** [comment] 2020-03-29 20:59
Thank you! <3

**Comment by victoriatomzik** [comment] 2020-03-29 21:01
Btw, I don't know if you're familiar with this one: https://github.com/1tayH/noisy
It's got pretty nice config file, excluding json, js, css files and other unnecessary stuff. Maybe worth giving it a try?
